### ISSUE TITLE
Path with two segments does not work

### ISSUE THREAD

**Issue by pavel163** [jauntybrain/flow-links-extension#1]
Hi. 
I use flowlinks extension. I created url with 2 segments in path
<img width="390" alt="Снимок экрана 2023-12-11 в 12 46 21" src="https://github.com/jauntybrain/flow-links-extension/assets/9054609/8737e8ad-997a-4d05-a3a9-969d6838602c">
And it doesn't work. I get 404

**Comment by jauntybrain** [comment]
Hi! Thanks for reporting this. 

Multi-level paths are not currently available, but I am implementing them right now. This feature should be available in an update later this week, and I will reply to this issue once it's out.

Thank you for your patience!

**Comment by jauntybrain** [comment]
This is now fixed in update 1.0.3. Closing this issue.
