### ISSUE TITLE
Programmatically create links

### ISSUE THREAD

**Issue by PasqualePuzio** [jauntybrain/flow-links-extension#11]
Hi,

we were wondering if this project supports the creation of links programmatically, meaning via an API.

If not, is there a way to achieve that?

Thanks

**Comment by jauntybrain** [comment]
Hello!

Since FlowLinks are stored in a Firestore collection, you can use existing Firestore APIs to modify said collection. You can use Firestore REST API or SDKs for Flutter/React/etc. to do so.

Please let me know if this helps!
