### ISSUE TITLE
Typo mistake

### ISSUE THREAD

**Issue by Ashish-Raturi** [jauntybrain/flow-links-extension#4]
hi in firebase funciton **ext-firebase-flow-links-initialize** index.html file line number 81 you missed to add w

it's like this, and because of that it's not redirect android user to the respected store.
<img width="767" alt="Screenshot 2024-02-11 at 11 30 32 AM" src="https://github.com/jauntybrain/flow-links-extension/assets/50191855/516c919e-ceb2-4614-a50d-94f1095fc9ca">

**Comment by jauntybrain** [comment]
Hi @Ashish-Raturi! 

Thanks for reporting this, very good catch. Will fix and release a new version ASAP.

**Comment by Ashish-Raturi** [comment]
Thanks you can you release now. I need it. Thanks for the extension also.

**Comment by jauntybrain** [comment]
Until the update is live, please feel free to edit and deploy Cloud Function `ext-firebase-flow-links-api` in your project.

**Comment by Ashish-Raturi** [comment]
i edited the function, but how can i update the website?

**Comment by Ashish-Raturi** [comment]
by the way both function. **ext-firebase-flow-links-initialize** and **ext-firebase-flow-links-api** have this typo

**Comment by jauntybrain** [comment]
What website are you referring to? If it's the Firebase Hosting website, it is hosted from the `ext-firebase-flow-links-api ` Cloud Function, so redeploying the function will automatically update the website.

Both functions come from the same codebase, so it makes sense for them both to have the typo.

**Comment by Ashish-Raturi** [comment]
hmm got it thanks

**Comment by jauntybrain** [comment]
@Ashish-Raturi this issue is fixed in version 0.1.5. It should be available for update today/tomorrow.
